#!/usr/bin/env bash
#
# Agency Full Bolt-On Installer
#
# This script bolts the full agency-agents collection onto your Pi project.
# Source: https://github.com/msitarzewski/agency-agents
#
# Usage:
#   ./install.sh [target-dir]
#
# Example:
#   ./install.sh ~/my-pi-project
#

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TARGET_DIR="${1:-.}"

echo "=== Agency Full Bolt-On Installer ==="
echo "Target: $TARGET_DIR"
echo ""

# Check for gh CLI
if ! command -v gh &> /dev/null; then
    echo "Error: GitHub CLI (gh) is required."
    echo "Install: https://cli.github.com/"
    exit 1
fi

# Create directories
mkdir -p "$TARGET_DIR/.pi/agents/engineering"
mkdir -p "$TARGET_DIR/.pi/agents/design"
mkdir -p "$TARGET_DIR/.pi/agents/sales"
mkdir -p "$TARGET_DIR/.pi/agents/marketing"
mkdir -p "$TARGET_DIR/.pi/agents/product"
mkdir -p "$TARGET_DIR/.pi/agents/pm"
mkdir -p "$TARGET_DIR/.pi/agents/testing"
mkdir -p "$TARGET_DIR/.pi/agents/support"
mkdir -p "$TARGET_DIR/.pi/agents/specialized"

REPO="msitarzewski/agency-agents"

fetch_agent() {
    local src="$1"
    local dst="$2"
    local name=$(basename "$src" .md)

    # Use raw GitHub URL instead of API (more reliable)
    local url="https://raw.githubusercontent.com/$REPO/main/$src"
    if curl -sSL "$url" -o "$dst" 2>/dev/null; then
        if [ -s "$dst" ]; then
            echo "  ✓ $name"
        else
            echo "  ✗ $name (empty)"
            rm -f "$dst"
        fi
    else
        echo "  ✗ $name (failed)"
    fi
}

echo "Fetching Engineering agents..."
fetch_agent "engineering/engineering-frontend-developer.md" "$TARGET_DIR/.pi/agents/engineering/frontend-developer.md"
fetch_agent "engineering/engineering-backend-architect.md" "$TARGET_DIR/.pi/agents/engineering/backend-architect.md"
fetch_agent "engineering/engineering-mobile-app-builder.md" "$TARGET_DIR/.pi/agents/engineering/mobile-app-builder.md"
fetch_agent "engineering/engineering-ai-engineer.md" "$TARGET_DIR/.pi/agents/engineering/ai-engineer.md"
fetch_agent "engineering/engineering-devops-automator.md" "$TARGET_DIR/.pi/agents/engineering/devops-automator.md"
fetch_agent "engineering/engineering-code-reviewer.md" "$TARGET_DIR/.pi/agents/engineering/code-reviewer.md"
fetch_agent "engineering/engineering-security-engineer.md" "$TARGET_DIR/.pi/agents/engineering/security-engineer.md"
fetch_agent "engineering/engineering-database-optimizer.md" "$TARGET_DIR/.pi/agents/engineering/database-optimizer.md"
fetch_agent "engineering/engineering-git-workflow-master.md" "$TARGET_DIR/.pi/agents/engineering/git-workflow-master.md"

echo ""
echo "Fetching Sales agents..."
fetch_agent "sales/sales-outbound-strategist.md" "$TARGET_DIR/.pi/agents/sales/outbound-strategist.md"
fetch_agent "sales/sales-deal-strategist.md" "$TARGET_DIR/.pi/agents/sales/deal-strategist.md"
fetch_agent "sales/sales-pipeline-analyst.md" "$TARGET_DIR/.pi/agents/sales/pipeline-analyst.md"
fetch_agent "sales/sales-account-strategist.md" "$TARGET_DIR/.pi/agents/sales/account-strategist.md"

echo ""
echo "Fetching Design agents..."
fetch_agent "design/design-ui-designer.md" "$TARGET_DIR/.pi/agents/design/ui-designer.md"
fetch_agent "design/design-ux-researcher.md" "$TARGET_DIR/.pi/agents/design/ux-researcher.md"

echo ""
echo "Fetching Marketing agents..."
fetch_agent "marketing/marketing-growth-hacker.md" "$TARGET_DIR/.pi/agents/marketing/growth-hacker.md"
fetch_agent "marketing/marketing-seo-specialist.md" "$TARGET_DIR/.pi/agents/marketing/seo-specialist.md"

echo ""
echo "Fetching Product agents..."
fetch_agent "product/product-sprint-prioritizer.md" "$TARGET_DIR/.pi/agents/product/sprint-prioritizer.md"
fetch_agent "product/product-trend-researcher.md" "$TARGET_DIR/.pi/agents/product/trend-researcher.md"

echo ""
echo "Fetching Testing agents..."
fetch_agent "testing/testing-evidence-collector.md" "$TARGET_DIR/.pi/agents/testing/evidence-collector.md"
fetch_agent "testing/testing-accessibility-auditor.md" "$TARGET_DIR/.pi/agents/testing/accessibility-auditor.md"

echo ""
echo "Fetching Specialized agents..."
fetch_agent "specialized/specialized-mcp-builder.md" "$TARGET_DIR/.pi/agents/specialized/mcp-builder.md"
fetch_agent "specialized/specialized-document-generator.md" "$TARGET_DIR/.pi/agents/specialized/document-generator.md"

echo ""
echo "Creating teams.yaml..."
cat > "$TARGET_DIR/.pi/agents/teams.yaml" << 'EOF'
# Agency Teams Configuration
# Auto-generated by agency-full bolt-on

engineering:
  - frontend-developer
  - backend-architect
  - mobile-app-builder
  - ai-engineer
  - devops-automator
  - code-reviewer
  - security-engineer
  - database-optimizer
  - git-workflow-master

sales:
  - outbound-strategist
  - deal-strategist
  - pipeline-analyst
  - account-strategist

design:
  - ui-designer
  - ux-researcher

marketing:
  - growth-hacker
  - seo-specialist

product:
  - sprint-prioritizer
  - trend-researcher

testing:
  - evidence-collector
  - accessibility-auditor

specialized:
  - mcp-builder
  - document-generator
EOF

echo ""
echo "=== Installation Complete ==="
echo ""
echo "To use with Pi Agent extensions:"
echo "  1. Add to your justfile:"
echo "       ext-agency-full:"
echo "           pi -e extensions/agent-team.ts -e extensions/theme-cycler.ts"
echo ""
echo "  2. Run: just ext-agency-full"
echo ""
echo "The following teams are now available:"
echo "  - engineering (9 agents)"
echo "  - sales (4 agents)"
echo "  - design (2 agents)"
echo "  - marketing (2 agents)"
echo "  - product (2 agents)"
echo "  - testing (2 agents)"
echo "  - specialized (2 agents)"
echo ""
echo "Total: 23 agents ready to dispatch!"
